bcb_sgs:
  raw_dir: "data/01_raw/bcb/sgs"
  source: "BCB_SGS"
  series_meta:
    432:
      name: "SELIC"
      frequency: "D"
      unit: "% a.a."
    433:
      name: "IPCA"
      frequency: "M"
      unit: "%"

bcb_demab:
  raw_dir: "data/01_raw/bcb/demab/negociacoes_titulos_federais_secundario"
  source: "BCB_DEMAB"
  zip_prefix: "NegE"
